name: "Validation And Formatting"
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: "hacs/action@main"
        name: HACS Action
        with:
          CATEGORY: integration
      - uses: "home-assistant/actions/hassfest@master"
        name: Hass Fest

